name: GCC+LLD Build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0,4'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      buildPrefix:
        description: 'GCC build prefix'
        type: string
        default: "/opt/gcc"
        required: false
env:
      # GITHUB_EMAIL: ${{ secrets.EMAIL }}
      # GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      # GITHUB_USER: ${{ secrets.USERNAME }}
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  before_build:
    runs-on: [ ubuntu-latest ]
    outputs:
      GCC_BUILD_VERSION: ${{ steps.get.outputs.GCC_BUILD_VERSION }}
      GCC_BUILD_PREFIX: ${{ steps.get.outputs.GCC_BUILD_PREFIX }}
    # https://docs.github.com/zh/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#%E7%A4%BA%E4%BE%8B%E5%AE%9A%E4%B9%89%E4%BD%9C%E4%B8%9A%E7%9A%84%E8%BE%93%E5%87%BA  
    steps:
      - name: Get buildPrefix
        id: get
        run: |
          curl -sLo ver "https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=gcc/BASE-VER"
          export version=$(cat ver)
          echo "GCC_BUILD_VERSION=${version}" >> "$GITHUB_OUTPUT"
          export build_prefix="${{ github.event.inputs.buildPrefix }}"
          if [ "${{ github.event.inputs.buildPrefix }}" == "" ]; then build_prefix="/opt/gcc"; fi
          echo "GCC_BUILD_PREFIX=${build_prefix}" >> "$GITHUB_OUTPUT"

  build-arm64-tc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set build date
      id: get-date
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y systemd language-pack-zh-hans language-pack-zh-hans-base locales tree
        sudo locale-gen zh_CN.UTF-8; /usr/bin/localectl set-locale LANG=zh_CN.UTF-8 || true ; 
        /usr/bin/timedatectl set-timezone Asia/Shanghai || true; 
        /usr/bin/timedatectl set-ntp true || true;
        sudo apt-get install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma libc6-dev-i386 --fix-broken --fix-missing
    - name: Build
      run: |
        chmod a+x build-*.sh
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<b>Starting ARM64 GCC Build</b>"
        ./build-gcc.sh -a arm64
        ./build-lld.sh -a arm64
        script_dir=$(pwd)
        cd gcc-arm64
        ./bin/aarch64-elf-gcc -v 2>&1 | tee ../gcc-version
        ./bin/aarch64-elf-ld.lld -v 2>&1 | tee ../lld-arm64-version
        bash "$script_dir/strip-binaries.sh"
        cd ../ && cat lld-arm64-version >> gcc-version
    - name: Create tarball
      run: |
        tree .
        # tar -cvf eva-gcc-arm64-$(/bin/date -u '+%d%m%Y').xz gcc-arm64/*
        cd gcc-arm64
        zip -r -q -9 ../eva-gcc-arm64-$(/bin/date -u '+%d%m%Y').zip .

    - uses: actions/upload-artifact@main
      with:
       name: aarch64-tarball
       path: |
         *.zip
         gcc-version

  build-x86-tc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set build date
      id: get-date
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y systemd language-pack-zh-hans language-pack-zh-hans-base locales tree
        sudo locale-gen zh_CN.UTF-8; /usr/bin/localectl set-locale LANG=zh_CN.UTF-8 || true ; 
        /usr/bin/timedatectl set-timezone Asia/Shanghai || true; 
        /usr/bin/timedatectl set-ntp true || true;
        sudo apt-get install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma libc6-dev-i386 --fix-broken --fix-missing
    - name: Build
      run: |
        chmod a+x build-*.sh
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<b>Starting ARM (32-bit) GCC Build</b>"
        ./build-gcc.sh -a x86
        ./build-lld.sh -a x86
        script_dir=$(pwd)
        bash "$script_dir/strip-binaries.sh"
    - name: Create tarball
      run: |
        tree gcc-x86
        #tar -cvf eva-gcc-x86-$(/bin/date -u '+%d%m%Y').xz gcc-x86/*
        cd gcc-x86
        zip -r -q -9 ../eva-gcc-x86-$(/bin/date -u '+%d%m%Y').zip .
        

    - uses: actions/upload-artifact@main
      with:
       name: x86-tarball
       path: |
         *.zip

  build-in-centos7:
    runs-on: ubuntu-latest
    needs: before_build

    steps:
      - name: Checkout v4
        uses: actions/checkout@v4

      - name: Create build script
        run: |
          set -xe
          cat << 'EOF' > build.sh
          #!/bin/bash
          set -xe
          echo 'LANG=zh_CN.UTF-8' >> /etc/environment
          echo 'LANGUAGE=zh_CN.UTF-8' >> /etc/environment
          echo 'LC_ALL=zh_CN.UTF-8' >> /etc/environment
          echo 'LC_CTYPE=zh_CN.UTF-8' >> /etc/environment
          # curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
          # curl -o /etc/yum.repos.d/epel.repo https://mirrors.aliyun.com/repo/epel-7.repo

          # 定义镜像列表
          MIRRORS=(
              "http://mirror.rackspace.com/centos-vault/7.9.2009/"
              "https://mirror.nsc.liu.se/centos-store/7.9.2009/"
              "https://linuxsoft.cern.ch/centos-vault/7.9.2009/"
              "https://archive.kernel.org/centos-vault/7.9.2009/"
              "https://vault.centos.org/7.9.2009/"
              "http://mirrors.aliyun.com/centos-vault/7.9.2009"
          )

          # 初始化变量
          FASTEST_MIRROR=""
          FASTEST_TIME=99999

          echo "Testing mirror response times..."

          # 测试每个镜像的响应时间
          for MIRROR in "${MIRRORS[@]}"; do
              echo -n "Testing $MIRROR ... "
              # 使用 curl 测试响应时间
              TIME=$(curl -o /dev/null -s -w "%{time_total}\n" "$MIRROR")
              echo "$TIME seconds"

              # 比较响应时间，记录最快的镜像
              if (( $(echo "$TIME < $FASTEST_TIME" | bc -l) )); then
                  FASTEST_TIME=$TIME
                  FASTEST_MIRROR=$MIRROR
              fi
          done

          # 输出最快的镜像
          echo "-----------------------------------"
          echo "Fastest mirror: $FASTEST_MIRROR"
          echo "Response time: $FASTEST_TIME seconds"

          echo "[CentOS-Base]" > /etc/yum.repos.d/CentOS-Base.repo
          echo "name=CentOS-Base" >> /etc/yum.repos.d/CentOS-Base.repo
          echo "baseurl=$FASTEST_MIRROR" >> /etc/yum.repos.d/CentOS-Base.repo
          echo "gpgcheck=0" >> /etc/yum.repos.d/CentOS-Base.repo

          yum clean all
          yum makecache
          yum install -y epel-release
          ls -lh /etc/yum.repos.d/

          # echo "[buildlogs-cdn-centos-x86_64]" > /etc/yum.repos.d/centos7-devtoolset-12.repo
          # echo "name=devtoolset-12" >> /etc/yum.repos.d/centos7-devtoolset-12.repo
          # echo "baseurl=https://buildlogs.cdn.centos.org/c7-devtoolset-12.x86_64" >> /etc/yum.repos.d/centos7-devtoolset-12.repo
          # echo "gpgcheck=0" >> /etc/yum.repos.d/centos7-devtoolset-12.repo
          # echo "enabled=1" >> /etc/yum.repos.d/centos7-devtoolset-12.repo
          # yum -y update
          # yum -y install devtoolset-12 --nogpgcheck
          # scl enable devtoolset-12 bash
          # source /opt/rh/devtoolset-12/enable
          # gcc -v
          # make -v


          yum -y install devtoolset-10 --nogpgcheck
          scl enable devtoolset-10 bash
          source /opt/rh/devtoolset-10/enable
          gcc -v
          make -v

          yum -y install tzdata
          ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo 'Asia/Shanghai' > /etc/timezone
          yum update -y
          yum install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma libc6-dev-i386 ncurses-devel expat-devel binutils-devel gmp-devel make pkgconfig mpfr-devel gettext-devel zlib-devel lz4-devel xz xz-devel glibc-devel.i686 which clang lld bzip2 glibc glibc-devel
          yum install -y pcre-devel zlib-devel make git wget sed perl-IPC-Cmd GeoIP GeoIP-devel zip systemd autoconf automake libtool
          yum install -y perl-Test-Simple perl-FindBin perl-IPC-Cmd perl-Text-Template perl-File-Compare perl-File-Copy perl-Data-Dumper


          # TODO: Add more dynamic option handling
          while getopts a: flag; do
            case "${flag}" in
              a) arch=${OPTARG} ;;
              *) echo "Invalid argument passed" && exit 1 ;;
            esac
          done

          # TODO: Better target handling
          case "${arch}" in
            "arm") TARGET="arm-eabi" ;;
            "arm64") TARGET="aarch64-elf" ;;
            "arm64gnu") TARGET="aarch64-linux-gnu" ;;
            "x86") TARGET="x86_64-elf" ;;
          esac
          # Declare the number of jobs to run simultaneously
          JOBS=$(nproc --all)

          export WORK_DIR="$PWD"
          export PREFIX="$WORK_DIR/gcc-${arch}"
          export PATH="$PREFIX/bin:/usr/bin/core_perl:$PATH"
          export OPT_FLAGS="-flto -flto-compression-level=10 -O3 -pipe -ffunction-sections -fdata-sections"
          rm -rf "$WORK_DIR"/{binutils,build-binutils,build-gcc,gcc}

          echo "Downloading Pre-requisites"
          echo "Cloning binutils"
          git clone git://sourceware.org/git/binutils-gdb.git -b master binutils --depth=1
          sed -i '/^development=/s/true/false/' binutils/bfd/development.sh
          echo "Cloned binutils!"
          echo "Cloning GCC"
          git clone git://gcc.gnu.org/git/gcc.git -b master gcc --depth=1
          cd "${WORK_DIR}"
          echo "Downloaded prerequisites!"

          cd "${WORK_DIR}"
          echo "Building Binutils"
          mkdir build-binutils
          cd build-binutils
          env CFLAGS="$OPT_FLAGS" CXXFLAGS="$OPT_FLAGS" \
            ../binutils/configure --target="$TARGET" \
            --disable-docs \
            --disable-gdb \
            --disable-nls \
            --disable-werror \
            --enable-gold \
            --prefix="$PREFIX" \
            --with-pkgversion="Eva Binutils" \
            --with-sysroot
          make -j"$JOBS"
          make install -j"$JOBS"
          cd ../
          echo "Built Binutils, proceeding to next step...."

          cd "${WORK_DIR}"
          echo "Building GCC"
          cd gcc
          ./contrib/download_prerequisites
          echo "Bleeding Edge" > gcc/DEV-PHASE
          cd ../
          mkdir build-gcc
          cd build-gcc
          env CFLAGS="$OPT_FLAGS" CXXFLAGS="$OPT_FLAGS" \
            ../gcc/configure --target="$TARGET" \
            --with-bugurl=https://github.com/indiff/gcc-build \
            --disable-decimal-float \
            --disable-docs \
            --disable-gcov \
            --disable-libffi \
            --disable-libgomp \
            --disable-libmudflap \
            --disable-libquadmath \
            --disable-libstdcxx-pch \
            --disable-nls \
            --disable-shared \
            --enable-bootstrap \
            --enable-multilib \
            --enable-gnu-unique-object \
            --enable-plugin  \
            --enable-gnu-indirect-functio \
            --enable-initfini-array \
            --enable-default-ssp \
            --enable-languages=c,c++,fortran,lto \
            --enable-threads=posix \
            --prefix="$PREFIX" \
            --with-gnu-as \
            --with-gnu-ld \
            --with-headers="/usr/include" \
            --with-linker-hash-style=gnu \
            --with-newlib \
            --with-pkgversion="Eva GCC" \
            --with-sysroot

          make all-gcc -j"$JOBS"
          make all-target-libgcc -j"$JOBS"
          make install-gcc -j"$JOBS"
          make install-target-libgcc -j"$JOBS"
          echo "Built GCC!"

          cd "${WORK_DIR}"
          CUR_DIR=$(pwd)
          X86S=$(which strip)
          A64S=$(which aarch64-linux-gnu-strip)
          A32S=$(which arm-linux-gnu-strip)

          find "$CUR_DIR" -type f -exec file {} \; >.file-idx

          grep "x86" .file-idx |
            grep "not strip" | grep -v "relocatable" |
            tr ':' ' ' | awk '{print $1}' |
            while read -r file; do $X86S "$file"; done

          grep "ARM" .file-idx | grep "aarch64" |
            grep "not strip" | grep -v "relocatable" |
            tr ':' ' ' | awk '{print $1}' |
            while read -r file; do $A64S "$file"; done

          grep "ARM" .file-idx | grep "32.bit" |
            grep "not strip" | grep -v "relocatable" |
            tr ':' ' ' | awk '{print $1}' |
            while read -r file; do $A32S "$file"; done

          rm ".file-idx"

          cd gcc-x86
          zip -r -q -9 /workspace/centos7-eva-gcc-x86-$(/bin/date -u '+%d%m%Y').zip .
          # get glibc Version
          echo $(cut -d- -f2 <<<$(rpm -q glibc)) >> /workspace/glibc_version.txt
          EOF
          chmod +x build.sh
          
      # - name: Upload build.sh
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build.sh
      #     path: build.sh     

      - name: Build GCC in Docker
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          timedatectl status
          sudo mkdir -p ${{ needs.before_build.outputs.GCC_BUILD_PREFIX }}
          sudo chown -R 777 ${{ needs.before_build.outputs.GCC_BUILD_PREFIX }}
          docker run --cpus="$(nproc --all)" -u root --rm -v ${{ github.workspace }}:/workspace -v ${{ needs.before_build.outputs.GCC_BUILD_PREFIX }}:${{ needs.before_build.outputs.GCC_BUILD_PREFIX }} -w /workspace centos:7 /bin/bash -c "/workspace/build.sh -a x86"
          export build_timestamp="$(date +'%Y%m%d_%H%M')"
          export glib_version="$(cat glibc_version.txt)"
          export size_kb=$(du -k opt_nginx.zip | cut -f1)
          tree ${{ needs.before_build.outputs.GCC_BUILD_PREFIX }}

      - name: Upload GCC package
        uses: actions/upload-artifact@v4
        with:
          name: nginx-centos7-${{ needs.before_build.outputs.NGINX_BUILD_VERSION }}
          path: |
            ${{ github.workspace }}/*.zip
       

  publish-release:
      needs: [build-arm64-tc,build-x86-tc,build-in-centos7]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Restoring artifacts
          uses: actions/download-artifact@main
          with:
            path: ${{ github.workspace }}
        - name: Release Tag
          id: release_tag
          run: echo "TAG_NAME='$(date -u +%d%m%Y)'" >> $GITHUB_ENV
        - name: Create Release
          run: |
            gh release create ${{ env.TAG_NAME }} -F aarch64-tarball/gcc-version */*.zip

  send-day:
    needs: [publish-release]
    runs-on: ubuntu-latest

    steps:
      - name: Send telegram messages
        run: |
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="It's $(date +%A) my dudes!"
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="The year is $(date +'%j' | awk '{printf "%.2f\n", $0 / 365.25 * 100}')% complete. Time is flying."
